services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history 
    depends_on:
      - db
      - redis

  js:
    build: .
    entrypoint: ./js-entrypoint.sh
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  css:
    build: .
    entrypoint: ./css-entrypoint.sh
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
  bundle:
